name: CI/CD to Codespace

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/spring-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}

      # - name: Deploy to Google IDX via Tailscale
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
      #   run: |
      #     ssh -o StrictHostKeyChecking=no ${{ secrets.IDX_USER }}@${{ secrets.IDX_HOST }} << EOF
      #       docker pull $DOCKER_USER/spring-app:latest
      #       docker stop spring-app || true
      #       docker rm spring-app || true

      #       docker run -d --name spring-app \
      #         -p 8080:8080 \
      #         -e DB_HOST="${{ secrets.DB_HOST }}" \
      #         -e DB_PORT="${{ secrets.DB_PORT }}" \
      #         -e DB_NAME="${{ secrets.DB_NAME }}" \
      #         -e DB_USERNAME="${{ secrets.DB_USER }}" \
      #         -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
      #         -e AIRLAB_API_KEY="${{ secrets.AIRLAB_API_KEY }}" \
      #         $DOCKER_USER/spring-app:latest
      #     EOF



      # --- PHáº¦N CODESPACE (COMMENTED OUT) ---
      - name: Deploy to Codespace via GH CLI
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CODESPACE_NAME: sturdy-bassoon-555pw7qqgx6h74q
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
          run: |
            gh auth setup-git

            
            gh codespace ssh -c $CODESPACE_NAME --command "
              docker pull $DOCKER_USER/spring-app:latest &&
              docker stop spring-app || true &&
              docker rm spring-app || true &&
              docker run -d --name spring-app \
                -p 8080:8080 \
                -e DB_HOST='${{ secrets.DB_HOST }}' \
                -e DB_PORT='${{ secrets.DB_PORT }}' \
              -e DB_NAME='${{ secrets.DB_NAME }}' \
              -e DB_USERNAME='${{ secrets.DB_USER }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              $DOCKER_USER/spring-app:latest &&
            docker ps -a
            "